#pragma once
#include "Memory.h"
#include "Debug.h"
#include "Misc.h"
#include "Math.h"
#include "Time.h"
#include "FileIO.h"
#include "Rendering.h"
#include "Window.h"
#include "World.h"
#include "ManagerBase.h"

#include "Camera.h"
#include "DirectionalLight.h"
#include "PointLight.h"
#include "SpotLight.h"
